files:
  include: '**/*.s+(a|c)ss'
  ignore: '**/node_modules/**/*'
rules:
  attribute-quotes: 2
  border-zero: 2
  brace-style: 2
  class-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'pascalcase'
  declarations-before-nesting: 2
  empty-line-between-blocks: 2
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 2
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format: 2
  hex-length: 2
  hex-notation: 2
  id-name-format:
    - 2
    -
      allow-leading-underscore: false
  indentation: 2
  max-line-length: 2
  mixin-name-format: 2
  leading-zero: 2
  nesting-depth:
    - 2
    -
      max-depth: 3
  no-color-keywords: 2
  no-color-literals: 0
  no-css-comments: 2
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-trailing-whitespace: 2
  one-declaration-per-line: 2
  property-sort-order: 0
  pseudo-element: 2
  quotes: 2
  single-line-per-selector: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format:
    - 2
    -
      allow-leading-underscore: false
  variable-for-property:
    - 2
    -
      properties:
        - 'color'
        - 'background-color'
        - 'font-size'
  zero-unit: 2